# Generated by Django 4.2.1 on 2023-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alamat_pengiriman',
        ),
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kode_pos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='negara',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='AlamatPengiriman',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
